# Bluetooth
CONFIG_BT=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_MAX_CONN=1

# SoftDevice Controller with LLPM
CONFIG_BT_LL_SOFTDEVICE=y
CONFIG_BT_CTLR_SDC_LLPM=y
CONFIG_BT_CTLR_SDC_MAX_CONN_EVENT_LEN_DEFAULT=3000
CONFIG_BT_HCI_VS_EVT_USER=y
CONFIG_BT_CONN_PARAM_ANY=y

# NCS bt_scan module
CONFIG_BT_SCAN=y
CONFIG_BT_SCAN_FILTER_ENABLE=y
CONFIG_BT_SCAN_UUID_CNT=1

# GATT discovery manager
CONFIG_BT_GATT_DM=y
CONFIG_HEAP_MEM_POOL_SIZE=2048

# GPIO
CONFIG_GPIO=y

# USB composite (CDC ACM + HID gamepad)
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_USBD_HID_SUPPORT=y

# Speed optimization (overridden by release.conf with size opt)
CONFIG_SPEED_OPTIMIZATIONS=y
